### ISSUE TITLE
Error: Unknown subtree

### ISSUE THREAD

**Issue by raypatterson** [plitex/git-subtree#1]
Hi,

I am getting the error in the subject when trying to add a subtree. The remote is added OK, but then `_cmd_add` method is called a 2nd time and the 2nd arg becomes `--prefix={path/to/repo}`.

I haven't dug too deep into the `shell.js` but it looks like this line:

``` js
shell.execute('git', ['subtree', 'add', '--prefix=' + config.localFolder, subtree, config.branch, '--squash'], callbackAsync, function(data) { process.stdout.write(data) });
```

Is somehow calling `_cmd_add`.

I put in a check to shift to the 3rd arg which is the key to the subtree config but it appears to get caught in a loop, calling `_cmd_add`.

I'm running:
git 2.5.0
npm 2.12.1
node 0.12.7

Let me know if I can provide any more information.

Thanks!

**Comment by plitex** [comment]
Hi,

I didn't tested with git 2.5.0. Could you provide the output error to have more info?
Which OS are you using?

**Comment by plitex** [comment]
I've tested some commands in windows with 1.9.5 and ubuntu with 1.9.5 and 2.5.0 and for me it's working.

**Comment by raypatterson** [comment]
Hi, Thanks for testing!

The error is exactly as thrown in the code "Error: Unknown subtree".

I'm running OS X 10.10.4.

**Comment by plitex** [comment]
This error is shown if no configuration exists for the subtree name in the command. Could you paste your subtrees.json (removing private data) and the command you executed to try to test in my side?

**Comment by raypatterson** [comment]
It is reading the config correctly on the first execution of `_cmd_add`, as I mentioned, however that method is being called again with the wrong argument signature.

(Original report)

> The remote is added OK, but then _cmd_add method is called a 2nd time and the 2nd arg becomes --prefix={path/to/repo}.

If there was no config, the remote add would have failed.

**Comment by plitex** [comment]
Hi, I've been looking into this, and I cannot reproduce your problem. I'm really sorry.

**Comment by raypatterson** [comment]
Hey no problem, feel free to close. It might be some sort of Git CLI weirdness from an alias. Thanks for looking into! Great project!
